# Generated by Django 5.0 on 2024-09-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
