# Generated by Django 5.0 on 2024-09-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_task_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='edit',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
