# Generated by Django 5.0 on 2024-09-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_todoitem_created_at_todoitem_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='created_at',
        ),
    ]
